export const GERMAN_COURTS: string[] = [
  'Aachen',
  'Altenburg',
  'Amberg',
  'Ansbach',
  'Apolda',
  'Arnsberg',
  'Arnstadt Zweigstelle Ilmenau',
  'Arnstadt',
  'Aschaffenburg',
  'Augsburg',
  'Aurich',
  'Bad Hersfeld',
  'Bad Homburg v.d.H.',
  'Bad Kreuznach',
  'Bad Oeynhausen',
  'Bad Salzungen',
  'Bamberg',
  'Bayreuth',
  'Berlin (Charlottenburg)',
  'Bielefeld',
  'Bochum',
  'Bonn',
  'Braunschweig',
  'Bremen',
  'Chemnitz',
  'Coburg',
  'Coesfeld',
  'Cottbus',
  'Darmstadt',
  'Deggendorf',
  'Dortmund',
  'Dresden',
  'Duisburg',
  'Düren',
  'Düsseldorf',
  'Eisenach',
  'Erfurt',
  'Eschwege',
  'Essen',
  'Flensburg',
  'Frankfurt am Main',
  'Frankfurt/Oder',
  'Freiburg',
  'Friedberg',
  'Fritzlar',
  'Fulda',
  'Fürth',
  'Gelsenkirchen',
  'Gera',
  'Gießen',
  'Gotha',
  'Greiz',
  'Göttingen',
  'Gütersloh',
  'Hagen',
  'Hamburg',
  'Hamm',
  'Hanau',
  'Hannover',
  'Heilbad Heiligenstadt',
  'Hildburghausen',
  'Hildesheim',
  'Hof',
  'Homburg',
  'Ingolstadt',
  'Iserlohn',
  'Jena',
  'Kaiserslautern',
  'Kassel',
  'Kempten (Allgäu)',
  'Kiel',
  'Kleve',
  'Koblenz',
  'Korbach',
  'Krefeld',
  'Köln',
  'Königstein',
  'Landau',
  'Landshut',
  'Langenfeld',
  'Lebach',
  'Leipzig',
  'Lemgo',
  'Limburg',
  'Ludwigshafen a.Rhein (Ludwigshafen)',
  'Lübeck',
  'Lüneburg',
  'Mainz',
  'Mannheim',
  'Marburg',
  'Meiningen',
  'Memmingen',
  'Merzig',
  'Montabaur',
  'Mönchengladbach',
  'Mühlhausen',
  'München',
  'Münster',
  'Neubrandenburg',
  'Neunkirchen',
  'Neuruppin',
  'Neuss',
  'Nordhausen',
  'Nürnberg',
  'Offenbach am Main',
  'Oldenburg (Oldenburg)',
  'Osnabrück',
  'Ottweiler',
  'Paderborn',
  'Passau',
  'Pinneberg',
  'Potsdam',
  'Pößneck Zweigstelle Bad Lobenstein',
  'Pößneck',
  'Recklinghausen',
  'Regensburg',
  'Rostock',
  'Rudolstadt Zweigstelle Saalfeld',
  'Rudolstadt',
  'Saarbrücken',
  'Saarlouis',
  'Schweinfurt',
  'Schwerin',
  'Siegburg',
  'Siegen',
  'Sondershausen',
  'Sonneberg',
  'St. Ingbert (St Ingbert)',
  'St. Wendel (St Wendel)',
  'Stadthagen',
  'Stadtroda',
  'Steinfurt',
  'Stendal',
  'Stralsund',
  'Straubing',
  'Stuttgart',
  'Suhl',
  'Sömmerda',
  'Tostedt',
  'Traunstein',
  'Ulm',
  'Völklingen',
  'Walsrode',
  'Weiden i. d. OPf.',
  'Weimar',
  'Wetzlar',
  'Wiesbaden',
  'Wittlich',
  'Wuppertal',
  'Würzburg',
  'Zweibrücken'
]
