name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      -   name: Install Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '14'
            architecture: x64

      -   name: Git checkout for source code analysis
          uses: actions/checkout@v2

      -   name: Install Dependencies
          run: |
            npm ci

      -   name: Cache Node.js modules
          uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}

      -   name: Run unit tests
          run: |
            npm run lint
            npm run test:ci
            npm run codecov
      -   name: Build
          if: github.ref == 'refs/heads/main'
          run: |
            npm run build
      -   name: Cache dist folder
          uses: actions/cache@v2
          with:
            path: dist
            key: company-id-validation-dist-${{ github.run_id }}
  release:
    uses: RedFroggy/company-id-validator/.github/workflows/release.yml@main
    needs: build
