name: release
description: Run semantic release
permissions:
  contents: read
  pull-requests: read
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: release
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          cp package.json dist/main
          npm run semantic-release

