name: Release
permissions:
  contents: read
  pull-requests: read
on:
  workflow_call:

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout for source code analysis
        uses: actions/checkout@v3
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: release
        run: |
          ls -ail
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          cp package.json dist/main
          npm run release

