name: Release
permissions:
  contents: read
  pull-requests: read
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout for source code analysis
        uses: actions/checkout@v2
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Cache dist folder
        uses: actions/cache@v2
        with:
          path: dist
          key: company-id-validation-dist-${{ hashFiles('dist/**') }}
      - name: release
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          cp package.json dist/main
          npm run semantic-release

