name: Release
permissions:
  contents: write
  issues: write
  pull-requests: write
on:
  workflow_call:

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout for source code analysis
        uses: actions/checkout@v3

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-node1-${{ hashFiles('**/package-lock.json') }}

      - name: Cache dist folder
        uses: actions/cache@v3
        with:
          path: dist
          key: company-id-validation-dist-${{ github.run_id }}

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          ls -ail
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          cp package.json dist/main
          npm run release

